'use strict'
/**
 * spoonacular API
 * The spoonacular Nutrition, Recipe, and Food API allows you to access over 380,000 recipes, thousands of ingredients, 800,000 food products, and 100,000 menu items. Our food ontology and semantic recipe search engine makes it possible to search for recipes using natural language queries, such as \"gluten free brownies without sugar\" or \"low fat vegan cupcakes.\" You can automatically calculate the nutritional information for any recipe, analyze recipe costs, visualize ingredient lists, find recipes for what's in your fridge, find recipes based on special diets, nutritional requirements, or favorite ingredients, classify recipes into types and cuisines, convert ingredient amounts, or even compute an entire meal plan. With our powerful API, you can create many kinds of food and especially nutrition apps.  Special diets/dietary requirements currently available include: vegan, vegetarian, pescetarian, gluten free, grain free, dairy free, high protein, whole 30, low sodium, low carb, Paleo, ketogenic, FODMAP, and Primal.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@spoonacular.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
var __importDefault =
  (this && this.__importDefault) ||
  function (mod) {
    return mod && mod.__esModule ? mod : { default: mod }
  }
Object.defineProperty(exports, '__esModule', { value: true })
const ApiClient_1 = __importDefault(require('../ApiClient'))
const InlineResponse20028Nutrition_1 = __importDefault(
  require('./InlineResponse20028Nutrition')
)
const InlineResponse20028Servings_1 = __importDefault(
  require('./InlineResponse20028Servings')
)
const InlineResponse20030Ingredients_1 = __importDefault(
  require('./InlineResponse20030Ingredients')
)
/**
 * The InlineResponse20030 model module.
 * @module com.spoonacular.client/com.spoonacular.client.model/InlineResponse20030
 * @version 1.0
 */
class InlineResponse20030 {
  /**
   * Constructs a new <code>InlineResponse20030</code>.
   * @alias module:com.spoonacular.client/com.spoonacular.client.model/InlineResponse20030
   * @param id {Number}
   * @param title {String}
   * @param breadcrumbs {Array.<String>}
   * @param imageType {String}
   * @param badges {Array.<String>}
   * @param importantBadges {Array.<String>}
   * @param ingredientCount {Number}
   * @param ingredientList {String}
   * @param ingredients {Array.<module:com.spoonacular.client/com.spoonacular.client.model/InlineResponse20030Ingredients>}
   * @param likes {Number}
   * @param aisle {String}
   * @param nutrition {module:com.spoonacular.client/com.spoonacular.client.model/InlineResponse20028Nutrition}
   * @param price {Number}
   * @param servings {module:com.spoonacular.client/com.spoonacular.client.model/InlineResponse20028Servings}
   * @param spoonacularScore {Number}
   */
  constructor(
    id,
    title,
    breadcrumbs,
    imageType,
    badges,
    importantBadges,
    ingredientCount,
    ingredientList,
    ingredients,
    likes,
    aisle,
    nutrition,
    price,
    servings,
    spoonacularScore
  ) {
    InlineResponse20030.initialize(
      this,
      id,
      title,
      breadcrumbs,
      imageType,
      badges,
      importantBadges,
      ingredientCount,
      ingredientList,
      ingredients,
      likes,
      aisle,
      nutrition,
      price,
      servings,
      spoonacularScore
    )
  }
  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(
    obj,
    id,
    title,
    breadcrumbs,
    imageType,
    badges,
    importantBadges,
    ingredientCount,
    ingredientList,
    ingredients,
    likes,
    aisle,
    nutrition,
    price,
    servings,
    spoonacularScore
  ) {
    obj['id'] = id
    obj['title'] = title
    obj['breadcrumbs'] = breadcrumbs
    obj['imageType'] = imageType
    obj['badges'] = badges
    obj['importantBadges'] = importantBadges
    obj['ingredientCount'] = ingredientCount
    obj['ingredientList'] = ingredientList
    obj['ingredients'] = ingredients
    obj['likes'] = likes
    obj['aisle'] = aisle
    obj['nutrition'] = nutrition
    obj['price'] = price
    obj['servings'] = servings
    obj['spoonacularScore'] = spoonacularScore
  }
  /**
   * Constructs a <code>InlineResponse20030</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.spoonacular.client/com.spoonacular.client.model/InlineResponse20030} obj Optional instance to populate.
   * @return {module:com.spoonacular.client/com.spoonacular.client.model/InlineResponse20030} The populated <code>InlineResponse20030</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse20030()
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient_1.default.convertToType(data['id'], 'Number')
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient_1.default.convertToType(
          data['title'],
          'String'
        )
      }
      if (data.hasOwnProperty('breadcrumbs')) {
        obj['breadcrumbs'] = ApiClient_1.default.convertToType(
          data['breadcrumbs'],
          ['String']
        )
      }
      if (data.hasOwnProperty('imageType')) {
        obj['imageType'] = ApiClient_1.default.convertToType(
          data['imageType'],
          'String'
        )
      }
      if (data.hasOwnProperty('badges')) {
        obj['badges'] = ApiClient_1.default.convertToType(data['badges'], [
          'String',
        ])
      }
      if (data.hasOwnProperty('importantBadges')) {
        obj['importantBadges'] = ApiClient_1.default.convertToType(
          data['importantBadges'],
          ['String']
        )
      }
      if (data.hasOwnProperty('ingredientCount')) {
        obj['ingredientCount'] = ApiClient_1.default.convertToType(
          data['ingredientCount'],
          'Number'
        )
      }
      if (data.hasOwnProperty('generatedText')) {
        obj['generatedText'] = ApiClient_1.default.convertToType(
          data['generatedText'],
          Object
        )
      }
      if (data.hasOwnProperty('ingredientList')) {
        obj['ingredientList'] = ApiClient_1.default.convertToType(
          data['ingredientList'],
          'String'
        )
      }
      if (data.hasOwnProperty('ingredients')) {
        obj['ingredients'] = ApiClient_1.default.convertToType(
          data['ingredients'],
          [InlineResponse20030Ingredients_1.default]
        )
      }
      if (data.hasOwnProperty('likes')) {
        obj['likes'] = ApiClient_1.default.convertToType(
          data['likes'],
          'Number'
        )
      }
      if (data.hasOwnProperty('aisle')) {
        obj['aisle'] = ApiClient_1.default.convertToType(
          data['aisle'],
          'String'
        )
      }
      if (data.hasOwnProperty('nutrition')) {
        obj['nutrition'] =
          InlineResponse20028Nutrition_1.default.constructFromObject(
            data['nutrition']
          )
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = ApiClient_1.default.convertToType(
          data['price'],
          'Number'
        )
      }
      if (data.hasOwnProperty('servings')) {
        obj['servings'] =
          InlineResponse20028Servings_1.default.constructFromObject(
            data['servings']
          )
      }
      if (data.hasOwnProperty('spoonacularScore')) {
        obj['spoonacularScore'] = ApiClient_1.default.convertToType(
          data['spoonacularScore'],
          'Number'
        )
      }
    }
    return obj
  }
}
/**
 * @member {Number} id
 */
InlineResponse20030.prototype['id'] = undefined
/**
 * @member {String} title
 */
InlineResponse20030.prototype['title'] = undefined
/**
 * @member {Array.<String>} breadcrumbs
 */
InlineResponse20030.prototype['breadcrumbs'] = undefined
/**
 * @member {String} imageType
 */
InlineResponse20030.prototype['imageType'] = undefined
/**
 * @member {Array.<String>} badges
 */
InlineResponse20030.prototype['badges'] = undefined
/**
 * @member {Array.<String>} importantBadges
 */
InlineResponse20030.prototype['importantBadges'] = undefined
/**
 * @member {Number} ingredientCount
 */
InlineResponse20030.prototype['ingredientCount'] = undefined
/**
 * @member {Object} generatedText
 */
InlineResponse20030.prototype['generatedText'] = undefined
/**
 * @member {String} ingredientList
 */
InlineResponse20030.prototype['ingredientList'] = undefined
/**
 * @member {Array.<module:com.spoonacular.client/com.spoonacular.client.model/InlineResponse20030Ingredients>} ingredients
 */
InlineResponse20030.prototype['ingredients'] = undefined
/**
 * @member {Number} likes
 */
InlineResponse20030.prototype['likes'] = undefined
/**
 * @member {String} aisle
 */
InlineResponse20030.prototype['aisle'] = undefined
/**
 * @member {module:com.spoonacular.client/com.spoonacular.client.model/InlineResponse20028Nutrition} nutrition
 */
InlineResponse20030.prototype['nutrition'] = undefined
/**
 * @member {Number} price
 */
InlineResponse20030.prototype['price'] = undefined
/**
 * @member {module:com.spoonacular.client/com.spoonacular.client.model/InlineResponse20028Servings} servings
 */
InlineResponse20030.prototype['servings'] = undefined
/**
 * @member {Number} spoonacularScore
 */
InlineResponse20030.prototype['spoonacularScore'] = undefined
exports.default = InlineResponse20030
